app = 'macroanalysis-empty-haze-9152'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [http_service.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = "macroanalysis_data"
  destination = "/data"

[processes]
  app = "gunicorn MacroAnalysis.app:app --bind 0.0.0.0:8080"
